name: Update stats

on:
  push:
    branches: [ main ]

  workflow_dispatch:
  
  schedule:
  - cron: "0 0 * * 5" # Every Friday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Install dependancies
      run: |
        npm install
    - name: Run update
      run: |
        node main.js
    - name: Commit files
      run: |
        git config --local user.email "dv7.esports+github@gmail.com"
        git config --local user.name "DV7 Progress Manager"
        git commit -m "Update the stats of the rosters" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
